apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dtag-dev
  name: registrationform
  labels:
    app: registrationform
    version: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registrationform
      version: dev
  template:
    metadata:
      name: registrationform
      labels:
        app: registrationform
        version: dev
    spec:
      containers:
      - name: loginform
        image: mohammadaszadali/
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 2Gi
---

apiVersion: v1
kind: Service
metadata:
  namespace: dtag-dev
  name: registrationform
  labels:
    app: registrationform
    version: dev
spec:
  type: LoadBalancer
  ports:
  - targetPort: 80
    port: 80
  selector:
    app: registrationform
    version: dev
